import type { IconType } from 'react-icons';
import {
  SiVuedotjs,
  SiReact,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiSass,
  SiTailwindcss,
  SiBootstrap,
  SiRedux,
  SiNextdotjs,
  SiNuxtdotjs,
  SiAngular,
  SiSvelte,
  SiNodedotjs,
  SiExpress,
  SiFastify,
  SiNestjs,
  SiDjango,
  SiFlask,
  SiVite,
  SiWebpack,
  SiBabel,
  SiRollupdotjs,
  SiEslint,
  SiPrettier,
  SiVitest,
  SiJest,
  SiTestinglibrary,
  SiCypress,
  SiNpm,
  SiPnpm,
  SiYarn,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiLinux,
  SiAmazonwebservices,
  SiGooglecloud,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiMariadb,
  SiSqlite,
  SiRedis,
  SiElasticsearch,
  SiGraphql,
  SiRabbitmq,
  SiApachekafka,
  SiSpring,
  SiSpringboot,
  SiPython,
  SiGo,
  SiRust,
  SiPhp,
  SiKotlin,
  SiSwift,
  SiCplusplus,
  SiSharp,
  SiNginx,
  SiGithub,
  SiGitlab,
  SiJenkins,
  SiPostman,
  SiSwagger,
} from 'react-icons/si';

const ICON_MAP: Record<string, IconType> = {
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss3,
  css3: SiCss3,
  sass: SiSass,
  scss: SiSass,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  bootstrap: SiBootstrap,
  vue: SiVuedotjs,
  vuejs: SiVuedotjs,
  react: SiReact,
  redux: SiRedux,
  next: SiNextdotjs,
  nextjs: SiNextdotjs,
  nuxt: SiNuxtdotjs,
  nuxtjs: SiNuxtdotjs,
  angular: SiAngular,
  svelte: SiSvelte,
  typescript: SiTypescript,
  ts: SiTypescript,
  javascript: SiJavascript,
  js: SiJavascript,
  node: SiNodedotjs,
  nodejs: SiNodedotjs,
  express: SiExpress,
  fastify: SiFastify,
  nest: SiNestjs,
  nestjs: SiNestjs,
  django: SiDjango,
  flask: SiFlask,
  vite: SiVite,
  webpack: SiWebpack,
  babel: SiBabel,
  rollup: SiRollupdotjs,
  eslint: SiEslint,
  prettier: SiPrettier,
  vitest: SiVitest,
  jest: SiJest,
  playwright: SiTestinglibrary,
  cypress: SiCypress,
  npm: SiNpm,
  pnpm: SiPnpm,
  yarn: SiYarn,
  pinia: SiVuedotjs,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  terraform: SiTerraform,
  linux: SiLinux,
  aws: SiAmazonwebservices,
  amazonwebservices: SiAmazonwebservices,
  gcp: SiGooglecloud,
  googlecloud: SiGooglecloud,
  azure: SiGooglecloud,
  microsoftazure: SiGooglecloud,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  mongodb: SiMongodb,
  mariadb: SiMariadb,
  sqlite: SiSqlite,
  redis: SiRedis,
  elasticsearch: SiElasticsearch,
  graphql: SiGraphql,
  rabbitmq: SiRabbitmq,
  kafka: SiApachekafka,
  apachekafka: SiApachekafka,
  spring: SiSpring,
  springboot: SiSpringboot,
  python: SiPython,
  go: SiGo,
  golang: SiGo,
  rust: SiRust,
  php: SiPhp,
  kotlin: SiKotlin,
  swift: SiSwift,
  'c++': SiCplusplus,
  cplusplus: SiCplusplus,
  'c#': SiSharp,
  csharp: SiSharp,
  nginx: SiNginx,
  github: SiGithub,
  gitlab: SiGitlab,
  jenkins: SiJenkins,
  postman: SiPostman,
  swagger: SiSwagger,
};

const normalize = (value: string): string =>
  value
    .toLowerCase()
    .replace(/[.\-_/()\s]/g, '')
    .trim();

export const getTechIcon = (label: string): IconType | undefined => ICON_MAP[normalize(label)];

export const splitTechValues = (text: string): string[] =>
  text
    .split(/[，,\/|·\s]+/)
    .map((item) => item.trim())
    .filter(Boolean);
